apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::036692858685:role/GitHubActionsCICDroleVSS
      username: github-actions
      groups:
        - system:masters
