replicaCount: 2
image:
  tag: <IMAGE_TAG>
service:
  type: ClusterIP
  port: 5000
ingress:
  enabled: true
  hosts:
    - host: shop-ubuntu-dev.312ubuntu.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: backend-tls
      hosts:
        - shop-ubuntu-dev.312ubuntu.com
