#resolved but have error : 

# Backend - Build, tag, and push docker image to Amazon ECR

# 10 naming to 036692858685.dkr.ecr.us-east-1.amazonaws.com/proshop-backend:10c695d5f7e667802254f8511a742c52380ccf1d done
# 10 DONE 5.9s
# The push refers to repository [036692858685.dkr.ecr.us-east-1.amazonaws.com/proshop-backend]
# a59f8edde95e: Preparing
# a6966e7266fc: Preparing
# cc869e60d0bb: Preparing
# dfa25be46153: Preparing
# be322b479aee: Preparing
# d41bcd3a037b: Preparing
# fe0d845e767b: Preparing
# f25ec1d93a58: Preparing
# 794ce8b1b516: Preparing
# 3220beed9b06: Preparing
# 684f82921421: Preparing
# 9af5f53e8f62: Preparing
# fe0d845e767b: Waiting
# f25ec1d93a58: Waiting
# 794ce8b1b516: Waiting
# 3220beed9b06: Waiting
# 684f82921421: Waiting
# 9af5f53e8f62: Waiting
# d41bcd3a037b: Waiting
# name unknown: The repository with name 'proshop-backend' does not exist in the registry with id '036692858685'
# Error: Process completed with exit code 1.

name: proshop app Image CI

on:
  push:
    branches:
      - feature/**

# required permissions by GitHub Actions for assuming AWS IAM role
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"

jobs:
  proshop-app-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Set Environment Stage
        id: set-env-stage
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then echo "ENVIRONMENT_STAGE=production" >> $GITHUB_ENV; elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then echo "ENVIRONMENT_STAGE=staging" >> $GITHUB_ENV; else echo "ENVIRONMENT_STAGE=dev" >> $GITHUB_ENV; fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::036692858685:role/GitHubActionsCICDroleVSS
          role-session-name: GitHubActionsCICDrole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Backend - Build, tag, and push docker image to Amazon ECR
        if: github.ref != 'refs/heads/main'
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: proshop-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Frontend - Build, tag, and push docker image to Amazon ECR
        if: github.ref != 'refs/heads/main'
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: proshop-frontend
          IMAGE_TAG: ${{ github.sha }}
        working-directory: ./frontend
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG





#there was syntax error : 


# name: proshop app Image CI

# on:
#   push:
#     branches:
#       - feature/**

# # required permissions by GitHub Actions for assuming AWS IAM role
# permissions:
#   id-token: write
#   contents: read

# env:
#   AWS_REGION: "us-east-1"
#   ENVIRONMENT_STAGE: ${{ github.ref == 'refs/heads/main' ? 'production' : (github.ref == 'refs/heads/staging' ? 'staging' : 'dev') }}

# jobs:
#   proshop-app-build-and-deploy:
#     environment: ${{ github.ref == 'refs/heads/main' ? 'production' : (github.ref == 'refs/heads/staging' ? 'staging' : 'dev') }}
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Branch
#         uses: actions/checkout@v3

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           role-to-assume: ${{ vars.IAM_ROLE }}
#           role-session-name: GitHubActionsCICDrole
#           aws-region: ${{ env.AWS_REGION }}

#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v2

#       - name: Backend - Build, tag, and push docker image to Amazon ECR
#         if: github.ref != 'refs/heads/main'
#         env:
#           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           REPOSITORY: proshop-backend
#           IMAGE_TAG: ${{ github.sha }}
#         run: |
#           docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
#           docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

#       - name: Frontend - Build, tag, and push docker image to Amazon ECR
#         if: github.ref != 'refs/heads/main'
#         env:
#           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           REPOSITORY: proshop-frontend
#           IMAGE_TAG: ${{ github.sha }}
#         working-directory: ./frontend
#         run: |
#           docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
#           docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG