replicaCount: 2
image:
  tag: <IMAGE_TAG>
service:
  type: ClusterIP
  port: 5000
ingress:
  enabled: true
  hosts:
    - host: shop-centos-dev.312centos.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: frontend-tls
      hosts:
        - shop-centos-dev.312centos.com
