replicaCount: 1

image:
  repository: <ECR_REGISTRY>/proshop-frontend
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: shop-centos-dev.312centos.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
